### ISSUE TITLE
Incorrect LCSC product number (C713947)

### ISSUE THREAD

**Issue by ronaldmaas** [TheByteAttic/TalosES#1]
For the 10K resistor which features in several boards the incorrect product number, C713947, is added to the BOM files. It should be C714634. Although that resistor has a different tolerance. I guess the tolerance is not massively important. However the value of the resistor is. Just want to stop people ordering blindly of the BOM.

**Comment by TheByteAttic** [comment]
Some boards in TalosES do use discrete resistors. Which BoM are you referring to, specifically? The BoM is generated automatically by the CAD tool, directly from the schematic.

**Comment by ronaldmaas** [comment]
All the BOM files, the 4 of the different cards and the motherboard. The manufacturer part is MF1/4W-1Ω±1%T52, which refers to a 1Ohm resistor. Maybe something not quite linked correctly?

**Comment by TheByteAttic** [comment]
Thanks. I will investigate this as soon as I get home on Sunday (on the road right now, slow Internet).

**Comment by TheByteAttic** [comment]
Apologies for the delay, Ronald, this fell through the cracks. It's all corrected now, for all five boards; all five BoM files are updated to use LCSC part number C2903232.
